### ISSUE TITLE
Powerworld R290 Monoblock support

### ISSUE THREAD

**Issue by netforceatg** [PiterPiotr/Sprsun-PC#1]
Hello, I have a PowerWorld PW040 (11kW R290 Monoblock), which seems to use the similar control board(ELECHICO model CC1010B) as the newer Sprsun(ELECHICO model CC902?).

Seems there are many names by this heatpump. Sunrain, Mango, Poland and probabaly more

Seems that parts of the modbus interface register is the same as the Sprsun, but not all. Any chance on getting this powerworld modbus interface supported?

[PW58329--CC1010B--MODBUS Communication Protocol V1.0_POWER WORLD R290(1).pdf](https://github.com/user-attachments/files/17071617/PW58329--CC1010B--MODBUS.Communication.Protocol.V1.0_POWER.WORLD.R290.1.pdf)

[POWER WORLD R290 Heat Pump Users' Manual (Technical Manual) -(20230524) V2.0 (2).pdf](https://github.com/user-attachments/files/17071742/POWER.WORLD.R290.Heat.Pump.Users.Manual.Technical.Manual.-.20230524.V2.0.2.pdf)

![image](https://github.com/user-attachments/assets/d3cf737b-5938-48ab-8b40-2f5509b011e3)

**Comment by PiterPiotr** [comment]
Unfortunately I don't know this brand. It's a bit different. You'd have to try connecting it yourself.
